### ISSUE TITLE
mpox clade typing

### ISSUE THREAD

**Issue by lukebsnell** [epi2me-labs/wf-mpx#6]
### Is your feature related to a problem?

would be useful if the wf typed to clade, given the mpox PHEIC for clade 1b.

### Describe the solution you'd like

^

### Describe alternatives you've considered

^

### Additional context

https://www.who.int/news/item/14-08-2024-who-director-general-declares-mpox-outbreak-a-public-health-emergency-of-international-concern

**Comment by bede** [comment]
Hi Luke,
The newly released v1.1.1 workflow types the reference-based consensus assembly using Nextclade, and will also attempt to type the *de novo* assembly if that option is enabled.

Thanks,
Bede

**Comment by cjalder** [comment]
Close as completed
